import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { createHash, randomUUID } from 'node:crypto';
import { Repository } from 'typeorm';
import { BudgetEntity } from '../../database/entities/budget.entity';
import { BudgetPeriodEntity } from '../../database/entities/budget-period.entity';
import { TransactionEntity } from '../../database/entities/transaction.entity';
import { RecurringRuleEntity } from '../../database/entities/recurring-rule.entity';
import { RecurringOccurrenceEntity } from '../../database/entities/recurring-occurrence.entity';
import { InstallmentPlanEntity } from '../../database/entities/installment-plan.entity';
import { InstallmentObligationEntity } from '../../database/entities/installment-obligation.entity';
import { CreditCardTermEntity } from '../../database/entities/credit-card-term.entity';
import { ImportBatchEntity } from '../../database/entities/import-batch.entity';
import { ImportRowEntity } from '../../database/entities/import-row.entity';
import { ApplicationSettingEntity } from '../../database/entities/application-setting.entity';
import { OutboxEventEntity } from '../../database/entities/outbox-event.entity';
import { CategoryEntity } from '../../database/entities/category.entity';
import { AccountEntity } from '../../database/entities/account.entity';
import type { RequestOwner } from '../../shared/domain/request-owner';
import { assertLocalDate, localDateFromIso, resolvePeriod, type PeriodPreset } from '../../shared/domain/period';
import { RealtimeEventsService } from '../../shared/realtime/realtime-events.service';

const currency = (value?: string) => (value || process.env.CURRENCY || 'UAH').toUpperCase();
const positive = (value: unknown) => Number.isInteger(value) && Number(value) > 0;
type BudgetCadence = 'monthly' | 'quarterly' | 'yearly';

const budgetPeriod = (value: string, cadence: BudgetCadence) => {
  const [year, month] = value.split('-').map(Number);
  const startMonth = cadence === 'quarterly' ? Math.floor((month - 1) / 3) * 3 : cadence === 'yearly' ? 0 : month - 1;
  const durationMonths = cadence === 'quarterly' ? 3 : cadence === 'yearly' ? 12 : 1;
  const start = new Date(Date.UTC(year, startMonth, 1));
  const end = new Date(Date.UTC(year, startMonth + durationMonths, 1));
  return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10) };
};

const assertBudgetCadence = (value: unknown): BudgetCadence => {
  if (value !== 'monthly' && value !== 'quarterly' && value !== 'yearly') throw new BadRequestException('Budget cadence must be monthly, quarterly, or yearly');
  return value;
};
@Injectable()
export class ExtendedFinanceService {
  constructor(
    @InjectRepository(BudgetEntity) private budgets: Repository<BudgetEntity>, @InjectRepository(BudgetPeriodEntity) private budgetPeriods: Repository<BudgetPeriodEntity>,
    @InjectRepository(TransactionEntity) private transactions: Repository<TransactionEntity>, @InjectRepository(RecurringRuleEntity) private rules: Repository<RecurringRuleEntity>,
    @InjectRepository(RecurringOccurrenceEntity) private occurrences: Repository<RecurringOccurrenceEntity>, @InjectRepository(InstallmentPlanEntity) private plans: Repository<InstallmentPlanEntity>,
    @InjectRepository(InstallmentObligationEntity) private obligations: Repository<InstallmentObligationEntity>, @InjectRepository(CreditCardTermEntity) private creditTerms: Repository<CreditCardTermEntity>,
    @InjectRepository(ImportBatchEntity) private batches: Repository<ImportBatchEntity>, @InjectRepository(ImportRowEntity) private rows: Repository<ImportRowEntity>,
    @InjectRepository(ApplicationSettingEntity) private settingsRepo: Repository<ApplicationSettingEntity>,
    @InjectRepository(OutboxEventEntity) private outbox: Repository<OutboxEventEntity>, @InjectRepository(CategoryEntity) private categories:Repository<CategoryEntity>,
    @InjectRepository(AccountEntity) private accounts: Repository<AccountEntity>,
    private readonly realtime: RealtimeEventsService,
  ) {}
  private assertOwner(recordOwnerId: string, owner: RequestOwner, message: string) { if (!owner.isAdmin && recordOwnerId !== owner.id) throw new ForbiddenException(message); }
  async listBudgets(query:{preset?:PeriodPreset;from?:string;to?:string}={}) { const selected = resolvePeriod(query); const budgets = await this.budgets.find({ order: { name: 'ASC' } }); return Promise.all(budgets.map(b => this.budgetProgress(b.id, selected.from))); }
  async createBudget(i: Record<string, any>, owner: RequestOwner) { if (!i.name?.trim() || !positive(i.plannedAmountMinor)) throw new BadRequestException('Invalid budget'); const cadence = assertBudgetCadence(i.cadence || 'monthly'); const requestedStart = assertLocalDate(i.periodStart || localDateFromIso(new Date().toISOString()), 'periodStart'); const period = budgetPeriod(requestedStart, cadence); const budget = await this.budgets.save(this.budgets.create({ id: randomUUID(), ownerId: owner.id, name: i.name.trim(), categoryId: i.categoryId || null, projectId: i.projectId || null, periodStart: period.start, periodEnd: period.end, plannedAmountMinor: i.plannedAmountMinor, currency: currency(i.currency), active: true, cadence, rolloverEnabled: Boolean(i.rolloverEnabled), warningPercent: i.warningPercent ?? 80 })); await this.budgetPeriods.save(this.budgetPeriods.create({ id: randomUUID(), budgetId: budget.id, startOn: budget.periodStart, endOnExclusive: budget.periodEnd, plannedAmountMinor: budget.plannedAmountMinor, rolloverMinor: 0, status: 'open' })); await this.realtime.publishChanged('budget', budget.id); return this.budgetProgress(budget.id, requestedStart); }
  async budgetProgress(id: string, selectedStart?: string) { const b = await this.budgets.findOneBy({ id }); if (!b) throw new NotFoundException('Budget not found'); const cadence = assertBudgetCadence(b.cadence || 'monthly'); const period = budgetPeriod(selectedStart || b.periodStart, cadence); const txs = await this.transactions.find({ where: { type: 'expense' } });const categoryIds=new Set<string>();if(b.categoryId){categoryIds.add(b.categoryId);const all=await this.categories.find();let changed=true;while(changed){changed=false;for(const c of all)if(c.parentId&&categoryIds.has(c.parentId)&&!categoryIds.has(c.id)){categoryIds.add(c.id);changed=true;}}} const spentMinor = txs.filter(t => t.currency === b.currency && t.occurredOn >= period.start && t.occurredOn < period.end && (!b.categoryId || !!t.categoryId&&categoryIds.has(t.categoryId)) && (!b.projectId || t.projectId === b.projectId)).reduce((s,t)=>s+t.amountMinor,0); return { ...b, periodStart: period.start, periodEnd: period.end, spentMinor, remainingMinor: b.plannedAmountMinor-spentMinor, percentage: Math.round(spentMinor*100/b.plannedAmountMinor), exceeded: spentMinor>b.plannedAmountMinor }; }
  async updateBudget(id: string, i: Record<string, any>, owner: RequestOwner) { const b=await this.budgets.findOneBy({id}); if(!b) throw new NotFoundException('Budget not found'); this.assertOwner(b.ownerId,owner,'Only the budget owner can change it'); const cadence = assertBudgetCadence(i.cadence ?? b.cadence); const period = budgetPeriod(assertLocalDate(i.periodStart ?? b.periodStart, 'periodStart'), cadence); Object.assign(b, { ...i, cadence, periodStart: period.start, periodEnd: period.end }); const updated=await this.budgets.save(b); const current=await this.budgetPeriods.findOneBy({budgetId:id,startOn:b.periodStart}); if(current){ current.endOnExclusive=b.periodEnd; current.plannedAmountMinor=b.plannedAmountMinor; await this.budgetPeriods.save(current); } await this.realtime.publishChanged('budget', id); return this.budgetProgress(id); }
  async deleteBudget(id:string,owner:RequestOwner){ const b=await this.budgets.findOneBy({id});if(!b)throw new NotFoundException('Budget not found');this.assertOwner(b.ownerId,owner,'Only the budget owner can delete it');const r=await this.budgets.delete(id); if(!r.affected) throw new NotFoundException('Budget not found'); await this.realtime.publishChanged('budget', id); return {id,deleted:true}; }
  async rolloverBudget(id:string){const b=await this.budgets.findOneBy({id});if(!b)throw new NotFoundException('Budget not found');const cadence=assertBudgetCadence(b.cadence);const progress=await this.budgetProgress(id);const current=await this.budgetPeriods.findOneBy({budgetId:id,startOn:b.periodStart});if(current){current.status='closed';await this.budgetPeriods.save(current);}const rollover=b.rolloverEnabled?Math.max(0,progress.remainingMinor):0;const next=budgetPeriod(b.periodEnd,cadence);b.periodStart=next.start;b.periodEnd=next.end;await this.budgets.save(b);await this.budgetPeriods.save({id:randomUUID(),budgetId:id,startOn:b.periodStart,endOnExclusive:b.periodEnd,plannedAmountMinor:b.plannedAmountMinor,rolloverMinor:rollover,status:'open'});return this.budgetProgress(id);}
  async listOccurrences(){ return this.occurrences.find({order:{dueDate:'ASC'}}); }
  async generateOccurrences(days=90){ const rules=await this.rules.findBy({active:true}); const today=new Date(); const limit=new Date(today.getTime()+days*86400000); let created=0; for(const rule of rules){ let d=new Date(`${rule.startDate}T00:00:00Z`); while(d<=limit){ const due=d.toISOString().slice(0,10); if((!rule.endDate||due<=rule.endDate)&&!await this.occurrences.findOneBy({ruleId:rule.id,dueDate:due})){ await this.occurrences.save({id:randomUUID(),ruleId:rule.id,dueDate:due,status:'pending',transactionId:null,amountMinor:rule.amountMinor,description:rule.description}); created++; } if(rule.frequency==='weekly') d.setUTCDate(d.getUTCDate()+7); else if(rule.frequency==='quarterly') d.setUTCMonth(d.getUTCMonth()+3); else if(rule.frequency==='yearly') d.setUTCFullYear(d.getUTCFullYear()+1); else d.setUTCMonth(d.getUTCMonth()+1); } } return {created}; }
  async confirmOccurrence(id:string, owner:RequestOwner, accountId?:string){ const o=await this.occurrences.findOneBy({id}); if(!o) throw new NotFoundException('Occurrence not found'); if(o.status==='confirmed') return o; const r=await this.rules.findOneBy({id:o.ruleId}); if(!r) throw new NotFoundException('Recurring rule not found'); const selectedAccountId=accountId||r.accountId;if(!selectedAccountId)throw new BadRequestException('Choose an account for this payment');const account=await this.accounts.findOneBy({id:selectedAccountId});if(!account||account.archived)throw new BadRequestException('Selected account is unavailable');const now=new Date().toISOString(); const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:selectedAccountId,relatedAccountId:null,projectId:r.projectId,categoryId:r.categoryId,type:r.type,amountMinor:o.amountMinor??r.amountMinor,currency:r.currency,description:o.description??r.description,occurredAt:`${o.dueDate}T12:00:00.000Z`,occurredOn:o.dueDate,createdAt:now,updatedAt:now,transferGroupId:null,externalKey:`recurring:${o.id}`}); o.status='confirmed';o.transactionId=tx.id; await this.occurrences.save(o); await this.enqueue('briareus_transaction_created',{source:'recurring'}); await this.realtime.publish('transaction.created',{id:tx.id}); await this.realtime.publishChanged('recurring',r.id); return o; }
  async confirmOccurrenceWithAmount(id:string, owner:RequestOwner, accountId:string, amountMinor:number){ if(!positive(amountMinor))throw new BadRequestException('amountMinor must be a positive integer'); const o=await this.occurrences.findOneBy({id});if(!o)throw new NotFoundException('Occurrence not found');if(o.status==='confirmed')return o;const r=await this.rules.findOneBy({id:o.ruleId});if(!r)throw new NotFoundException('Recurring rule not found');const account=await this.accounts.findOneBy({id:accountId});if(!account||account.archived)throw new BadRequestException('Selected account is unavailable');const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId,relatedAccountId:null,projectId:r.projectId,categoryId:r.categoryId,type:r.type,amountMinor,currency:r.currency,description:o.description??r.description,occurredAt:`${o.dueDate}T12:00:00.000Z`,occurredOn:o.dueDate,createdAt:now,updatedAt:now,externalKey:`recurring:${o.id}`});o.status='confirmed';o.transactionId=tx.id;await this.occurrences.save(o);await this.enqueue('briareus_transaction_created',{source:'recurring'});await this.realtime.publish('transaction.created',{id:tx.id});await this.realtime.publishChanged('recurring',r.id);return o; }
  async skipOccurrence(id:string){const o=await this.occurrences.findOneBy({id});if(!o)throw new NotFoundException('Occurrence not found');o.status='skipped';const updated=await this.occurrences.save(o);await this.realtime.publishChanged('recurring',o.ruleId);return updated;}
  async updateRecurring(id:string,i:Record<string,unknown>,owner:RequestOwner){const r=await this.rules.findOneBy({id});if(!r)throw new NotFoundException('Recurring rule not found');this.assertOwner(r.ownerId,owner,'Only the recurring rule owner can change it');Object.assign(r,i);const updated=await this.rules.save(r);await this.realtime.publishChanged('recurring',id);return updated;}
  async archiveRecurring(id:string,owner:RequestOwner){const r=await this.rules.findOneBy({id});if(!r)throw new NotFoundException('Recurring rule not found');this.assertOwner(r.ownerId,owner,'Only the recurring rule owner can delete it');r.active=false;await this.rules.save(r);await this.occurrences.delete({ruleId:id,status:'pending'});await this.realtime.publishChanged('recurring',id);return r;}
  async listInstallments(){const plans=await this.plans.find({order:{firstDueDate:'ASC'}});return Promise.all(plans.map(async p=>({...p,obligations:await this.obligations.find({where:{planId:p.id},order:{sequenceNumber:'ASC'}})})));}
  async payObligation(id:string, owner:RequestOwner){const o=await this.obligations.findOneBy({id});if(!o)throw new NotFoundException('Obligation not found');if(o.status==='paid')return o;const p=await this.plans.findOneBy({id:o.planId});if(!p)throw new NotFoundException('Plan not found');const account=await this.accounts.findOneBy({id:p.accountId});if(!account)throw new NotFoundException('Account not found');if(account.type!=='credit_card')throw new BadRequestException('Installment payment account must be a credit card');const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:p.accountId,relatedAccountId:null,projectId:null,categoryId:null,type:'expense',amountMinor:o.amountMinor,currency:p.currency,description:`Розстрочка: ${p.name}`,occurredAt:now,occurredOn:now.slice(0,10),createdAt:now,updatedAt:now,transferGroupId:null,externalKey:`installment:${o.id}`});o.status='paid';o.transactionId=tx.id;o.paidAt=now;const updated=await this.obligations.save(o);await this.realtime.publish('transaction.created',{id:tx.id});await this.realtime.publishChanged('installment',p.id);return updated;}
  async repayInstallment(id:string,owner:RequestOwner){const pending=await this.obligations.findBy({planId:id,status:'pending'});for(const o of pending)await this.payObligation(o.id,owner);const p=await this.plans.findOneBy({id});if(!p)throw new NotFoundException('Plan not found');p.status='completed';await this.plans.save(p);await this.realtime.publishChanged('installment',id);return this.listInstallments();}
  getCreditTerms(accountId:string){return this.creditTerms.findOneBy({accountId});}
  async saveCreditTerms(accountId:string,i:Record<string,any>){if(!Number.isInteger(i.statementDay)||i.statementDay<1||i.statementDay>31||!['next_month_end','next_month_day','fixed_days'].includes(i.graceRule))throw new BadRequestException('Invalid credit terms');return this.creditTerms.save({accountId,statementDay:i.statementDay,paymentDay:i.paymentDay??null,graceRule:i.graceRule,fixedDays:i.fixedDays??null,warningDays:i.warningDays??5});}
  async creditSummary(accountId:string){const terms=await this.creditTerms.findOneBy({accountId});if(!terms)throw new NotFoundException('Credit terms not found');const txs=await this.transactions.find();const debt=txs.filter(t=>t.accountId===accountId).reduce((s,t)=>s+(t.type==='expense'?t.amountMinor:t.type==='income'?-t.amountMinor:0),0);const now=new Date();let deadline:Date;if(terms.graceRule==='fixed_days')deadline=new Date(now.getTime()+(terms.fixedDays||0)*86400000);else if(terms.graceRule==='next_month_end')deadline=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+2,0));else deadline=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,terms.paymentDay||terms.statementDay));const days=Math.ceil((deadline.getTime()-now.getTime())/86400000);return{accountId,debtMinor:Math.max(0,debt),deadlineOn:deadline.toISOString().slice(0,10),risk:days<0?'overdue':days===0?'due':days<=terms.warningDays?'approaching':'normal'};}
  async previewImport(i:Record<string,any>,owner:RequestOwner,idempotencyKey?:string){if(!i.accountId||!['csv','ofx'].includes(i.format)||typeof i.content!=='string'||Buffer.byteLength(i.content)>10*1024*1024)throw new BadRequestException('Invalid import');if(idempotencyKey){const existing=await this.batches.findOneBy({idempotencyKey});if(existing)return this.importReport(existing.id);}const batch=await this.batches.save({id:randomUUID(),ownerId:owner.id,accountId:i.accountId,format:i.format,currency:currency(i.currency),status:'preview',idempotencyKey:idempotencyKey||null,createdAt:new Date().toISOString(),confirmedAt:null});const parsed=i.format==='csv'?this.parseCsv(i.content):this.parseOfx(i.content);for(let n=0;n<parsed.length;n++){const row=parsed[n];const fingerprint=createHash('sha256').update(`${i.accountId}|${row.occurredOn}|${row.amountMinor}|${batch.currency}|${row.description}|${row.externalId||''}`).digest('hex');const duplicate=await this.transactions.findOneBy({externalKey:row.externalId?`import:${row.externalId}`:`import:${fingerprint}`});await this.rows.save({id:randomUUID(),batchId:batch.id,rowNumber:n+1,...row,fingerprint,status:duplicate?'duplicate':'new',error:null,transactionId:null});}return this.importReport(batch.id);}
  async confirmImport(id:string,owner:RequestOwner){const b=await this.batches.findOneBy({id});if(!b)throw new NotFoundException('Import not found');if(b.status==='imported')return this.importReport(id);for(const row of await this.rows.findBy({batchId:id})){if(row.status!=='new'||!row.amountMinor||!row.occurredOn||!row.type)continue;const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:b.accountId,relatedAccountId:null,projectId:null,categoryId:null,type:row.type,amountMinor:row.amountMinor,currency:b.currency,description:row.description,occurredAt:`${row.occurredOn}T12:00:00.000Z`,occurredOn:row.occurredOn,createdAt:now,updatedAt:now,transferGroupId:null,externalKey:row.externalId?`import:${row.externalId}`:`import:${row.fingerprint}`});row.status='imported';row.transactionId=tx.id;await this.rows.save(row);await this.realtime.publish('transaction.created',{id:tx.id});}b.status='imported';b.confirmedAt=new Date().toISOString();await this.batches.save(b);await this.enqueue('briareus_import_completed',{batchId:b.id});await this.realtime.publishChanged('import',b.id);return this.importReport(id);}
  async cancelImport(id:string){const b=await this.batches.findOneBy({id});if(!b)throw new NotFoundException('Import not found');if(b.status==='imported')throw new BadRequestException('Imported batch cannot be cancelled');b.status='cancelled';return this.batches.save(b);}
  async importReport(id:string){const batch=await this.batches.findOneBy({id});if(!batch)throw new NotFoundException('Import not found');return{...batch,rows:await this.rows.find({where:{batchId:id},order:{rowNumber:'ASC'}})};}
  private parseCsv(content:string){const lines=content.trim().split(/\r?\n/);return lines.slice(1).map(line=>{const [date,description,amount,type='expense',externalId]=line.split(/[;,]/).map(v=>v.trim().replace(/^"|"$/g,''));const normalized=amount.replace(',','.');const [whole,fraction='']=normalized.replace('-','').split('.');return{occurredOn:assertLocalDate(date,'date'),description,amountMinor:Number(whole)*100+Number((fraction+'00').slice(0,2)),type:(type==='income'||Number(amount)<0?'income':'expense'),externalId:externalId||null};});}
  private parseOfx(content:string){return [...content.matchAll(/<STMTTRN>[\s\S]*?<DTPOSTED>(\d{8})[\s\S]*?<TRNAMT>([-\d.]+)[\s\S]*?(?:<FITID>([^<\r\n]+))?[\s\S]*?(?:<NAME>([^<\r\n]+))?[\s\S]*?<\/STMTTRN>/gi)].map(m=>{const raw=Math.abs(Number(m[2]));return{occurredOn:`${m[1].slice(0,4)}-${m[1].slice(4,6)}-${m[1].slice(6,8)}`,amountMinor:Math.round(raw*100),type:Number(m[2])>=0?'income':'expense',externalId:m[3]||null,description:m[4]||null};});}
  async getSettings(){const rows=await this.settingsRepo.find();return Object.fromEntries(rows.map(r=>[r.key,JSON.parse(r.value)]));}
  async saveSettings(i:Record<string,unknown>){for(const [key,value] of Object.entries(i))await this.settingsRepo.save({key,value:JSON.stringify(value)});return this.getSettings();}
  async listPayments(query:{preset?:PeriodPreset;from?:string;to?:string}={}){const period=resolvePeriod(query),untilDays=this.daysUntil(period.to);if(untilDays>0)await this.generateOccurrences(untilDays);const [accounts,txs,rules,occurrences,plans]=await Promise.all([this.accounts.findBy({archived:false}),this.transactions.find(),this.rules.findBy({active:true}),this.occurrences.find({order:{dueDate:'ASC'}}),this.listInstallments()]);const accountById=new Map(accounts.map(a=>[a.id,a])),ruleById=new Map(rules.map(r=>[r.id,r]));const inPeriod=(date:string)=>date>=period.from&&date<period.to;const recurring=occurrences.filter(o=>o.status==='pending'&&inPeriod(o.dueDate)).map(o=>{const r=ruleById.get(o.ruleId),account=r?accountById.get(r.accountId):null;return{id:`recurring:${o.id}`,sourceId:o.id,kind:'recurring',status:o.status,dueDate:o.dueDate,title:o.description||r?.description||'Запланований платіж',accountId:r?.accountId||null,accountName:account?.name||'Рахунок',amountMinor:o.amountMinor??r?.amountMinor??0,currency:r?.currency||'UAH',action:'confirm_or_skip'};});const installments=plans.filter(p=>p.status!=='completed'&&p.status!=='cancelled').flatMap(p=>(p.obligations||[]).filter(o=>o.status!=='paid'&&inPeriod(o.dueDate)).map(o=>({id:`installment:${o.id}`,sourceId:o.id,kind:'installment',status:o.status,dueDate:o.dueDate,title:p.name,accountId:p.accountId,accountName:accountById.get(p.accountId)?.name||'Рахунок',amountMinor:o.amountMinor,currency:p.currency,action:'pay'})));const creditCards=accounts.filter(account=>account.type==='credit_card'&&account.creditLimitMinor!==null).flatMap(account=>this.creditPaymentItems(account,txs).filter(item=>inPeriod(item.dueDate)));const items=[...recurring,...installments,...creditCards].filter(item=>item.amountMinor>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.kind.localeCompare(b.kind)||a.title.localeCompare(b.title));const totals=Object.entries(items.reduce<Record<string,number>>((result,item)=>{result[item.currency]=(result[item.currency]||0)+item.amountMinor;return result;},{})).map(([currency,amountMinor])=>({currency,amountMinor}));return{period,items,totals};}
  async listCreditPayments(){const [accounts,txs]=await Promise.all([this.accounts.findBy({archived:false}),this.transactions.find()]);const current=localDateFromIso(new Date().toISOString()).slice(0,7);const [year,month]=current.split('-').map(Number);const next=new Date(Date.UTC(year,month,1)).toISOString().slice(0,7);return accounts.filter(account=>account.type==='credit_card'&&account.creditLimitMinor!==null).flatMap(account=>this.creditPaymentItems(account,txs)).filter(item=>item.dueDate.slice(0,7)===current||item.dueDate.slice(0,7)===next).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.title.localeCompare(b.title));}
  async exportJson(){return{exportedAt:new Date().toISOString(),accounts:[],transactions:await this.transactions.find(),budgets:await this.budgets.find(),recurring:await this.rules.find(),installments:await this.plans.find()};}
  private daysUntil(to:string){const today=new Date();const end=new Date(`${to}T00:00:00Z`);return Math.max(0,Math.ceil((end.getTime()-today.getTime())/86400000));}
  private accountDeltaForPayment(id:string,tx:TransactionEntity){if(tx.type==='income'&&tx.accountId===id)return tx.amountMinor;if(tx.type==='expense'&&tx.accountId===id)return-tx.amountMinor;if(tx.type==='transfer_out'&&tx.accountId===id)return-tx.amountMinor;if(tx.type==='transfer_in'&&tx.accountId===id)return tx.amountMinor;if(tx.type==='transfer')return tx.accountId===id?-tx.amountMinor:tx.relatedAccountId===id?tx.amountMinor:0;return 0;}
  private creditPaymentItems(account:AccountEntity, txs:TransactionEntity[]) {
    if (!account.gracePeriodRule) return [];
    const charges = new Map<string, { amountMinor: number; paidMinor: number; paidByDeadlineMinor: number; dueDate: string; firstDate: string }>();
    for (const tx of txs.filter(row => row.accountId === account.id && row.type === 'expense')) {
      const month = tx.occurredOn.slice(0, 7);
      const dueDate = this.creditDueDate(account, month);
      const current = charges.get(month) || { amountMinor: 0, paidMinor: 0, paidByDeadlineMinor: 0, dueDate, firstDate: tx.occurredOn };
      current.amountMinor += tx.amountMinor;
      current.firstDate = current.firstDate < tx.occurredOn ? current.firstDate : tx.occurredOn;
      charges.set(month, current);
    }
    const events = txs.filter(row => row.accountId === account.id && (row.type === 'expense' || row.type === 'income' || row.type === 'transfer_in')).sort((a,b)=>a.occurredOn.localeCompare(b.occurredOn)||a.occurredAt.localeCompare(b.occurredAt));
    const today = localDateFromIso(new Date().toISOString());
    let graceBlocked = false;
    const checkDeadlines = (until: string) => { for (const charge of charges.values()) if (charge.dueDate < until && charge.paidMinor < charge.amountMinor && charge.paidByDeadlineMinor < charge.amountMinor) graceBlocked = true; };
    for (const event of events) {
      checkDeadlines(event.occurredOn);
      if (event.type === 'expense') continue;
      let remaining = event.amountMinor;
      for (const month of [...charges.keys()].sort()) {
        const charge = charges.get(month)!;
        if (charge.firstDate > event.occurredOn) continue;
        const applied = Math.min(charge.amountMinor - charge.paidMinor, remaining);
        charge.paidMinor += applied;
        if (event.occurredOn <= charge.dueDate) charge.paidByDeadlineMinor += applied;
        remaining -= applied;
        if (!remaining) break;
      }
      if ([...charges.values()].filter(charge => charge.firstDate <= event.occurredOn).every(charge => charge.paidMinor >= charge.amountMinor)) graceBlocked = false;
    }
    checkDeadlines(today);
    return [...charges.entries()].filter(([,charge])=>charge.amountMinor-charge.paidMinor>0).map(([month,charge])=>({id:`credit-card:${account.id}:${month}`,sourceId:account.id,kind:'credit_card' as const,status:graceBlocked?'overdue':'pending',dueDate:charge.dueDate,title:account.name,accountId:account.id,accountName:account.name,amountMinor:charge.amountMinor-charge.paidMinor,currency:account.currency,action:'manual' as const}));
  }
  private creditDueDate(account:AccountEntity, month:string) { const [year,monthNumber]=month.split('-').map(Number); const nextMonth=new Date(Date.UTC(year,monthNumber,1)); if(account.gracePeriodRule==='next_month_end') return new Date(Date.UTC(nextMonth.getUTCFullYear(),nextMonth.getUTCMonth()+1,0)).toISOString().slice(0,10); return new Date(Date.UTC(nextMonth.getUTCFullYear(),nextMonth.getUTCMonth(),Math.min(account.gracePeriodDay||1,new Date(Date.UTC(nextMonth.getUTCFullYear(),nextMonth.getUTCMonth()+1,0)).getUTCDate()))).toISOString().slice(0,10); }
  private creditDeadline(account:AccountEntity){if(!account.gracePeriodRule)return null;const values=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:process.env.TZ||'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));const year=Number(values.year),month=Number(values.month);if(!Number.isInteger(year)||!Number.isInteger(month))return null;if(account.gracePeriodRule==='next_month_end')return new Date(Date.UTC(year,month+1,0)).toISOString().slice(0,10);if(!account.gracePeriodDay)return null;const lastDay=new Date(Date.UTC(year,month+1,0)).getUTCDate();return new Date(Date.UTC(year,month,Math.min(account.gracePeriodDay,lastDay))).toISOString().slice(0,10);}
  private enqueue(type:string,payload:Record<string,unknown>){const now=new Date().toISOString();return this.outbox.save({id:randomUUID(),type,payload:JSON.stringify(payload),status:'pending',attempts:0,nextAttemptAt:now,createdAt:now});}
}
