import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Repository } from 'typeorm';
import { BudgetEntity } from '../../database/entities/budget.entity';
import { BudgetPeriodEntity } from '../../database/entities/budget-period.entity';
import { TransactionEntity } from '../../database/entities/transaction.entity';
import { RecurringRuleEntity } from '../../database/entities/recurring-rule.entity';
import { RecurringOccurrenceEntity } from '../../database/entities/recurring-occurrence.entity';
import { InstallmentPlanEntity } from '../../database/entities/installment-plan.entity';
import { InstallmentObligationEntity } from '../../database/entities/installment-obligation.entity';
import { CreditCardTermEntity } from '../../database/entities/credit-card-term.entity';
import { ImportBatchEntity } from '../../database/entities/import-batch.entity';
import { ImportRowEntity } from '../../database/entities/import-row.entity';
import { ReceiptEntity } from '../../database/entities/receipt.entity';
import { ApplicationSettingEntity } from '../../database/entities/application-setting.entity';
import { OutboxEventEntity } from '../../database/entities/outbox-event.entity';
import { CategoryEntity } from '../../database/entities/category.entity';
import { AccountEntity } from '../../database/entities/account.entity';
import type { RequestOwner } from '../../shared/domain/request-owner';
import { assertLocalDate, resolvePeriod, type PeriodPreset } from '../../shared/domain/period';
import { RealtimeEventsService } from '../../shared/realtime/realtime-events.service';

const currency = (value?: string) => (value || process.env.CURRENCY || 'UAH').toUpperCase();
const positive = (value: unknown) => Number.isInteger(value) && Number(value) > 0;
@Injectable()
export class ExtendedFinanceService {
  constructor(
    @InjectRepository(BudgetEntity) private budgets: Repository<BudgetEntity>, @InjectRepository(BudgetPeriodEntity) private budgetPeriods: Repository<BudgetPeriodEntity>,
    @InjectRepository(TransactionEntity) private transactions: Repository<TransactionEntity>, @InjectRepository(RecurringRuleEntity) private rules: Repository<RecurringRuleEntity>,
    @InjectRepository(RecurringOccurrenceEntity) private occurrences: Repository<RecurringOccurrenceEntity>, @InjectRepository(InstallmentPlanEntity) private plans: Repository<InstallmentPlanEntity>,
    @InjectRepository(InstallmentObligationEntity) private obligations: Repository<InstallmentObligationEntity>, @InjectRepository(CreditCardTermEntity) private creditTerms: Repository<CreditCardTermEntity>,
    @InjectRepository(ImportBatchEntity) private batches: Repository<ImportBatchEntity>, @InjectRepository(ImportRowEntity) private rows: Repository<ImportRowEntity>,
    @InjectRepository(ReceiptEntity) private receipts: Repository<ReceiptEntity>, @InjectRepository(ApplicationSettingEntity) private settingsRepo: Repository<ApplicationSettingEntity>,
    @InjectRepository(OutboxEventEntity) private outbox: Repository<OutboxEventEntity>, @InjectRepository(CategoryEntity) private categories:Repository<CategoryEntity>,
    @InjectRepository(AccountEntity) private accounts: Repository<AccountEntity>,
    private readonly realtime: RealtimeEventsService,
  ) {}
  private assertOwner(recordOwnerId: string, owner: RequestOwner, message: string) { if (!owner.isAdmin && recordOwnerId !== owner.id) throw new ForbiddenException(message); }
  async listBudgets() { const budgets = await this.budgets.find({ order: { periodStart: 'DESC' } }); return Promise.all(budgets.map(b => this.budgetProgress(b.id))); }
  async createBudget(i: Record<string, any>, owner: RequestOwner) { if (!i.name?.trim() || !positive(i.plannedAmountMinor) || !i.periodStart || !i.periodEnd || i.periodStart >= i.periodEnd) throw new BadRequestException('Invalid budget'); const budget = await this.budgets.save(this.budgets.create({ id: randomUUID(), ownerId: owner.id, name: i.name.trim(), categoryId: i.categoryId || null, projectId: i.projectId || null, periodStart: assertLocalDate(i.periodStart, 'periodStart'), periodEnd: assertLocalDate(i.periodEnd, 'periodEnd'), plannedAmountMinor: i.plannedAmountMinor, currency: currency(i.currency), active: true, cadence: i.cadence || 'custom', rolloverEnabled: Boolean(i.rolloverEnabled), warningPercent: i.warningPercent ?? 80 })); await this.budgetPeriods.save(this.budgetPeriods.create({ id: randomUUID(), budgetId: budget.id, startOn: budget.periodStart, endOnExclusive: budget.periodEnd, plannedAmountMinor: budget.plannedAmountMinor, rolloverMinor: 0, status: 'open' })); await this.realtime.publishChanged('budget', budget.id); return this.budgetProgress(budget.id); }
  async budgetProgress(id: string) { const b = await this.budgets.findOneBy({ id }); if (!b) throw new NotFoundException('Budget not found'); const txs = await this.transactions.find({ where: { type: 'expense' } });const categoryIds=new Set<string>();if(b.categoryId){categoryIds.add(b.categoryId);const all=await this.categories.find();let changed=true;while(changed){changed=false;for(const c of all)if(c.parentId&&categoryIds.has(c.parentId)&&!categoryIds.has(c.id)){categoryIds.add(c.id);changed=true;}}} const spentMinor = txs.filter(t => t.currency === b.currency && t.occurredOn >= b.periodStart && t.occurredOn < b.periodEnd && (!b.categoryId || !!t.categoryId&&categoryIds.has(t.categoryId)) && (!b.projectId || t.projectId === b.projectId)).reduce((s,t)=>s+t.amountMinor,0); return { ...b, spentMinor, remainingMinor: b.plannedAmountMinor-spentMinor, percentage: Math.round(spentMinor*100/b.plannedAmountMinor), exceeded: spentMinor>b.plannedAmountMinor }; }
  async updateBudget(id: string, i: Record<string, any>, owner: RequestOwner) { const b=await this.budgets.findOneBy({id}); if(!b) throw new NotFoundException('Budget not found'); this.assertOwner(b.ownerId,owner,'Only the budget owner can change it'); Object.assign(b, i); const updated=await this.budgets.save(b); await this.realtime.publishChanged('budget', id); return updated; }
  async deleteBudget(id:string,owner:RequestOwner){ const b=await this.budgets.findOneBy({id});if(!b)throw new NotFoundException('Budget not found');this.assertOwner(b.ownerId,owner,'Only the budget owner can delete it');const r=await this.budgets.delete(id); if(!r.affected) throw new NotFoundException('Budget not found'); await this.realtime.publishChanged('budget', id); return {id,deleted:true}; }
  async rolloverBudget(id:string){const b=await this.budgets.findOneBy({id});if(!b)throw new NotFoundException('Budget not found');if(!['monthly','quarterly'].includes(b.cadence))throw new BadRequestException('Only recurring budgets can roll over');const progress=await this.budgetProgress(id),months=b.cadence==='quarterly'?3:1;const advance=(value:string)=>{const d=new Date(`${value}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+months);return d.toISOString().slice(0,10)};const current=await this.budgetPeriods.findOneBy({budgetId:id,startOn:b.periodStart});if(current){current.status='closed';await this.budgetPeriods.save(current);}const rollover=b.rolloverEnabled?Math.max(0,progress.remainingMinor):0;b.periodStart=advance(b.periodStart);b.periodEnd=advance(b.periodEnd);await this.budgets.save(b);await this.budgetPeriods.save({id:randomUUID(),budgetId:id,startOn:b.periodStart,endOnExclusive:b.periodEnd,plannedAmountMinor:b.plannedAmountMinor,rolloverMinor:rollover,status:'open'});return this.budgetProgress(id);}
  async listOccurrences(){ return this.occurrences.find({order:{dueDate:'ASC'}}); }
  async generateOccurrences(days=90){ const rules=await this.rules.findBy({active:true}); const today=new Date(); const limit=new Date(today.getTime()+days*86400000); let created=0; for(const rule of rules){ let d=new Date(`${rule.startDate}T00:00:00Z`); while(d<=limit){ const due=d.toISOString().slice(0,10); if((!rule.endDate||due<=rule.endDate)&&!await this.occurrences.findOneBy({ruleId:rule.id,dueDate:due})){ await this.occurrences.save({id:randomUUID(),ruleId:rule.id,dueDate:due,status:'pending',transactionId:null,amountMinor:rule.amountMinor,description:rule.description}); created++; } if(rule.frequency==='weekly') d.setUTCDate(d.getUTCDate()+7); else if(rule.frequency==='quarterly') d.setUTCMonth(d.getUTCMonth()+3); else if(rule.frequency==='yearly') d.setUTCFullYear(d.getUTCFullYear()+1); else d.setUTCMonth(d.getUTCMonth()+1); } } return {created}; }
  async confirmOccurrence(id:string, owner:RequestOwner, accountId?:string){ const o=await this.occurrences.findOneBy({id}); if(!o) throw new NotFoundException('Occurrence not found'); if(o.status==='confirmed') return o; const r=await this.rules.findOneBy({id:o.ruleId}); if(!r) throw new NotFoundException('Recurring rule not found'); const selectedAccountId=accountId||r.accountId;if(!selectedAccountId)throw new BadRequestException('Choose an account for this payment');const account=await this.accounts.findOneBy({id:selectedAccountId});if(!account||account.archived)throw new BadRequestException('Selected account is unavailable');const now=new Date().toISOString(); const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:selectedAccountId,relatedAccountId:null,projectId:r.projectId,categoryId:r.categoryId,type:r.type,amountMinor:o.amountMinor??r.amountMinor,currency:r.currency,description:o.description??r.description,occurredAt:`${o.dueDate}T12:00:00.000Z`,occurredOn:o.dueDate,createdAt:now,updatedAt:now,transferGroupId:null,externalKey:`recurring:${o.id}`}); o.status='confirmed';o.transactionId=tx.id; await this.occurrences.save(o); await this.enqueue('briareus_transaction_created',{source:'recurring'}); await this.realtime.publish('transaction.created',{id:tx.id}); await this.realtime.publishChanged('recurring',r.id); return o; }
  async confirmOccurrenceWithAmount(id:string, owner:RequestOwner, accountId:string, amountMinor:number){ if(!positive(amountMinor))throw new BadRequestException('amountMinor must be a positive integer'); const o=await this.occurrences.findOneBy({id});if(!o)throw new NotFoundException('Occurrence not found');if(o.status==='confirmed')return o;const r=await this.rules.findOneBy({id:o.ruleId});if(!r)throw new NotFoundException('Recurring rule not found');const account=await this.accounts.findOneBy({id:accountId});if(!account||account.archived)throw new BadRequestException('Selected account is unavailable');const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId,relatedAccountId:null,projectId:r.projectId,categoryId:r.categoryId,type:r.type,amountMinor,currency:r.currency,description:o.description??r.description,occurredAt:`${o.dueDate}T12:00:00.000Z`,occurredOn:o.dueDate,createdAt:now,updatedAt:now,externalKey:`recurring:${o.id}`});o.status='confirmed';o.transactionId=tx.id;await this.occurrences.save(o);await this.enqueue('briareus_transaction_created',{source:'recurring'});await this.realtime.publish('transaction.created',{id:tx.id});await this.realtime.publishChanged('recurring',r.id);return o; }
  async skipOccurrence(id:string){const o=await this.occurrences.findOneBy({id});if(!o)throw new NotFoundException('Occurrence not found');o.status='skipped';const updated=await this.occurrences.save(o);await this.realtime.publishChanged('recurring',o.ruleId);return updated;}
  async updateRecurring(id:string,i:Record<string,unknown>,owner:RequestOwner){const r=await this.rules.findOneBy({id});if(!r)throw new NotFoundException('Recurring rule not found');this.assertOwner(r.ownerId,owner,'Only the recurring rule owner can change it');Object.assign(r,i);const updated=await this.rules.save(r);await this.realtime.publishChanged('recurring',id);return updated;}
  async archiveRecurring(id:string,owner:RequestOwner){const r=await this.rules.findOneBy({id});if(!r)throw new NotFoundException('Recurring rule not found');this.assertOwner(r.ownerId,owner,'Only the recurring rule owner can delete it');r.active=false;await this.rules.save(r);await this.occurrences.delete({ruleId:id,status:'pending'});await this.realtime.publishChanged('recurring',id);return r;}
  async listInstallments(){const plans=await this.plans.find({order:{firstDueDate:'ASC'}});return Promise.all(plans.map(async p=>({...p,obligations:await this.obligations.find({where:{planId:p.id},order:{sequenceNumber:'ASC'}})})));}
  async payObligation(id:string, owner:RequestOwner){const o=await this.obligations.findOneBy({id});if(!o)throw new NotFoundException('Obligation not found');if(o.status==='paid')return o;const p=await this.plans.findOneBy({id:o.planId});if(!p)throw new NotFoundException('Plan not found');const account=await this.accounts.findOneBy({id:p.accountId});if(!account)throw new NotFoundException('Account not found');if(account.type!=='credit_card')throw new BadRequestException('Installment payment account must be a credit card');const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:p.accountId,relatedAccountId:null,projectId:null,categoryId:null,type:'expense',amountMinor:o.amountMinor,currency:p.currency,description:`Розстрочка: ${p.name}`,occurredAt:now,occurredOn:now.slice(0,10),createdAt:now,updatedAt:now,transferGroupId:null,externalKey:`installment:${o.id}`});o.status='paid';o.transactionId=tx.id;o.paidAt=now;const updated=await this.obligations.save(o);await this.realtime.publish('transaction.created',{id:tx.id});await this.realtime.publishChanged('installment',p.id);return updated;}
  async repayInstallment(id:string,owner:RequestOwner){const pending=await this.obligations.findBy({planId:id,status:'pending'});for(const o of pending)await this.payObligation(o.id,owner);const p=await this.plans.findOneBy({id});if(!p)throw new NotFoundException('Plan not found');p.status='completed';await this.plans.save(p);await this.realtime.publishChanged('installment',id);return this.listInstallments();}
  getCreditTerms(accountId:string){return this.creditTerms.findOneBy({accountId});}
  async saveCreditTerms(accountId:string,i:Record<string,any>){if(!Number.isInteger(i.statementDay)||i.statementDay<1||i.statementDay>31||!['next_month_end','next_month_day','fixed_days'].includes(i.graceRule))throw new BadRequestException('Invalid credit terms');return this.creditTerms.save({accountId,statementDay:i.statementDay,paymentDay:i.paymentDay??null,graceRule:i.graceRule,fixedDays:i.fixedDays??null,warningDays:i.warningDays??5});}
  async creditSummary(accountId:string){const terms=await this.creditTerms.findOneBy({accountId});if(!terms)throw new NotFoundException('Credit terms not found');const txs=await this.transactions.find();const debt=txs.filter(t=>t.accountId===accountId).reduce((s,t)=>s+(t.type==='expense'?t.amountMinor:t.type==='income'?-t.amountMinor:0),0);const now=new Date();let deadline:Date;if(terms.graceRule==='fixed_days')deadline=new Date(now.getTime()+(terms.fixedDays||0)*86400000);else if(terms.graceRule==='next_month_end')deadline=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+2,0));else deadline=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,terms.paymentDay||terms.statementDay));const days=Math.ceil((deadline.getTime()-now.getTime())/86400000);return{accountId,debtMinor:Math.max(0,debt),deadlineOn:deadline.toISOString().slice(0,10),risk:days<0?'overdue':days===0?'due':days<=terms.warningDays?'approaching':'normal'};}
  async previewImport(i:Record<string,any>,owner:RequestOwner,idempotencyKey?:string){if(!i.accountId||!['csv','ofx'].includes(i.format)||typeof i.content!=='string'||Buffer.byteLength(i.content)>10*1024*1024)throw new BadRequestException('Invalid import');if(idempotencyKey){const existing=await this.batches.findOneBy({idempotencyKey});if(existing)return this.importReport(existing.id);}const batch=await this.batches.save({id:randomUUID(),ownerId:owner.id,accountId:i.accountId,format:i.format,currency:currency(i.currency),status:'preview',idempotencyKey:idempotencyKey||null,createdAt:new Date().toISOString(),confirmedAt:null});const parsed=i.format==='csv'?this.parseCsv(i.content):this.parseOfx(i.content);for(let n=0;n<parsed.length;n++){const row=parsed[n];const fingerprint=createHash('sha256').update(`${i.accountId}|${row.occurredOn}|${row.amountMinor}|${batch.currency}|${row.description}|${row.externalId||''}`).digest('hex');const duplicate=await this.transactions.findOneBy({externalKey:row.externalId?`import:${row.externalId}`:`import:${fingerprint}`});await this.rows.save({id:randomUUID(),batchId:batch.id,rowNumber:n+1,...row,fingerprint,status:duplicate?'duplicate':'new',error:null,transactionId:null});}return this.importReport(batch.id);}
  async confirmImport(id:string,owner:RequestOwner){const b=await this.batches.findOneBy({id});if(!b)throw new NotFoundException('Import not found');if(b.status==='imported')return this.importReport(id);for(const row of await this.rows.findBy({batchId:id})){if(row.status!=='new'||!row.amountMinor||!row.occurredOn||!row.type)continue;const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:b.accountId,relatedAccountId:null,projectId:null,categoryId:null,type:row.type,amountMinor:row.amountMinor,currency:b.currency,description:row.description,occurredAt:`${row.occurredOn}T12:00:00.000Z`,occurredOn:row.occurredOn,createdAt:now,updatedAt:now,transferGroupId:null,externalKey:row.externalId?`import:${row.externalId}`:`import:${row.fingerprint}`});row.status='imported';row.transactionId=tx.id;await this.rows.save(row);await this.realtime.publish('transaction.created',{id:tx.id});}b.status='imported';b.confirmedAt=new Date().toISOString();await this.batches.save(b);await this.enqueue('briareus_import_completed',{batchId:b.id});await this.realtime.publishChanged('import',b.id);return this.importReport(id);}
  async cancelImport(id:string){const b=await this.batches.findOneBy({id});if(!b)throw new NotFoundException('Import not found');if(b.status==='imported')throw new BadRequestException('Imported batch cannot be cancelled');b.status='cancelled';return this.batches.save(b);}
  async importReport(id:string){const batch=await this.batches.findOneBy({id});if(!batch)throw new NotFoundException('Import not found');return{...batch,rows:await this.rows.find({where:{batchId:id},order:{rowNumber:'ASC'}})};}
  private parseCsv(content:string){const lines=content.trim().split(/\r?\n/);return lines.slice(1).map(line=>{const [date,description,amount,type='expense',externalId]=line.split(/[;,]/).map(v=>v.trim().replace(/^"|"$/g,''));const normalized=amount.replace(',','.');const [whole,fraction='']=normalized.replace('-','').split('.');return{occurredOn:assertLocalDate(date,'date'),description,amountMinor:Number(whole)*100+Number((fraction+'00').slice(0,2)),type:(type==='income'||Number(amount)<0?'income':'expense'),externalId:externalId||null};});}
  private parseOfx(content:string){return [...content.matchAll(/<STMTTRN>[\s\S]*?<DTPOSTED>(\d{8})[\s\S]*?<TRNAMT>([-\d.]+)[\s\S]*?(?:<FITID>([^<\r\n]+))?[\s\S]*?(?:<NAME>([^<\r\n]+))?[\s\S]*?<\/STMTTRN>/gi)].map(m=>{const raw=Math.abs(Number(m[2]));return{occurredOn:`${m[1].slice(0,4)}-${m[1].slice(4,6)}-${m[1].slice(6,8)}`,amountMinor:Math.round(raw*100),type:Number(m[2])>=0?'income':'expense',externalId:m[3]||null,description:m[4]||null};});}
  async createReceipt(i:Record<string,any>,owner:RequestOwner){const allowed:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};if(!allowed[i.mimeType]||typeof i.dataBase64!=='string')throw new BadRequestException('Only JPEG, PNG and WebP are allowed');const data=Buffer.from(i.dataBase64,'base64');if(data.length>10*1024*1024)throw new BadRequestException('Receipt exceeds 10 MiB');const id=randomUUID();const dir=join(process.env.DATA_DIR||'./data','receipts');await mkdir(dir,{recursive:true});const path=join(dir,`${id}.${allowed[i.mimeType]}`);await writeFile(path,data,{flag:'wx'});return this.receipts.save({id,ownerId:owner.id,status:'uploaded',fileName:String(i.fileName||'receipt'),mimeType:i.mimeType,storedPath:path,merchant:null,occurredOn:null,amountMinor:null,currency:null,accountId:null,categoryId:null,projectId:null,description:null,transactionId:null,createdAt:new Date().toISOString()});}
  async ocrReceipt(id:string,owner:RequestOwner){const receipt=await this.receipts.findOneBy({id});if(!receipt)throw new NotFoundException('Receipt not found');this.assertOwner(receipt.ownerId,owner,'Only the receipt owner can recognize it');const key=process.env.OPENAI_API_KEY;if(!key)throw new BadRequestException('OPENAI_API_KEY is not configured');const image=await readFile(receipt.storedPath);const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_OCR_MODEL||'gpt-5-mini',store:false,input:[{role:'user',content:[{type:'input_text',text:'Розпізнай український або російський чек. Вибери саме підсумкову суму до сплати. Не вгадуй: невідомі значення поверни null. Дату поверни у форматі YYYY-MM-DD, суму — десятковим числом у вигляді рядка.'},{type:'input_image',image_url:`data:${receipt.mimeType};base64,${image.toString('base64')}`,detail:'high'}]}],text:{format:{type:'json_schema',name:'receipt',strict:true,schema:{type:'object',additionalProperties:false,properties:{merchant:{type:['string','null']},occurredOn:{type:['string','null']},amount:{type:['string','null']},currency:{type:['string','null']},description:{type:['string','null']},confidence:{type:'number'}},required:['merchant','occurredOn','amount','currency','description','confidence']}}}})});if(!response.ok)throw new BadRequestException('OpenAI не зміг розпізнати чек');const result=await response.json() as {output_text?:string};if(!result.output_text)throw new BadRequestException('OCR returned no result');let parsed:{merchant:string|null;occurredOn:string|null;amount:string|null;currency:string|null;description:string|null;confidence:number};try{parsed=JSON.parse(result.output_text);}catch{throw new BadRequestException('OCR returned invalid result');}const normalizedAmount=parsed.amount?.replace(/\s/g,'').replace(',','.');const amountMinor=normalizedAmount&&/^\d+(\.\d{1,2})?$/.test(normalizedAmount)?Math.round(Number(normalizedAmount)*100):null;receipt.status='draft';receipt.merchant=parsed.merchant;receipt.occurredOn=parsed.occurredOn;receipt.amountMinor=amountMinor;receipt.currency=parsed.currency?.toUpperCase()||currency();receipt.description=parsed.description||parsed.merchant;await this.receipts.save(receipt);return{receiptId:id,merchant:receipt.merchant,occurredOn:receipt.occurredOn,amountMinor,currency:receipt.currency,description:receipt.description,categoryId:null,projectId:null,tags:['чек'],metadata:{source:'receipt_ocr',confidence:parsed.confidence}};}
  listReceipts(){return this.receipts.find({order:{createdAt:'DESC'}});}
  async updateReceipt(id:string,i:Record<string,any>){const r=await this.receipts.findOneBy({id});if(!r)throw new NotFoundException('Receipt not found');Object.assign(r,i,{status:'draft'});return this.receipts.save(r);}
  async confirmReceipt(id:string,owner:RequestOwner){const r=await this.receipts.findOneBy({id});if(!r)throw new NotFoundException('Receipt not found');if(!r.accountId||!r.occurredOn||!positive(r.amountMinor)||!r.currency)throw new BadRequestException('Receipt draft is incomplete');const now=new Date().toISOString();const tx=await this.transactions.save({id:randomUUID(),ownerId:owner.id,accountId:r.accountId,relatedAccountId:null,projectId:r.projectId,categoryId:r.categoryId,type:'expense',amountMinor:r.amountMinor!,currency:r.currency,description:r.description||r.merchant,occurredAt:`${r.occurredOn}T12:00:00.000Z`,occurredOn:r.occurredOn,createdAt:now,updatedAt:now,transferGroupId:null,externalKey:`receipt:${r.id}`});r.status='confirmed';r.transactionId=tx.id;return this.receipts.save(r);}
  async cancelReceipt(id:string){const r=await this.receipts.findOneBy({id});if(!r)throw new NotFoundException('Receipt not found');if(r.status==='confirmed')throw new BadRequestException('Confirmed receipt cannot be cancelled');r.status='cancelled';return this.receipts.save(r);}
  async deleteReceipt(id:string){const r=await this.receipts.findOneBy({id});if(!r)throw new NotFoundException('Receipt not found');if(r.status==='confirmed')throw new BadRequestException('Confirmed receipt cannot be deleted');await unlink(r.storedPath).catch(()=>undefined);await this.receipts.delete(id);return{id,deleted:true};}
  async getSettings(){const rows=await this.settingsRepo.find();return Object.fromEntries(rows.map(r=>[r.key,JSON.parse(r.value)]));}
  async saveSettings(i:Record<string,unknown>){for(const [key,value] of Object.entries(i))await this.settingsRepo.save({key,value:JSON.stringify(value)});return this.getSettings();}
  async listPayments(query:{preset?:PeriodPreset;from?:string;to?:string}={}){const period=resolvePeriod(query),untilDays=this.daysUntil(period.to);if(untilDays>0)await this.generateOccurrences(untilDays);const [accounts,txs,rules,occurrences,plans]=await Promise.all([this.accounts.findBy({archived:false}),this.transactions.find(),this.rules.findBy({active:true}),this.occurrences.find({order:{dueDate:'ASC'}}),this.listInstallments()]);const accountById=new Map(accounts.map(a=>[a.id,a])),ruleById=new Map(rules.map(r=>[r.id,r]));const inPeriod=(date:string)=>date>=period.from&&date<period.to;const recurring=occurrences.filter(o=>o.status==='pending'&&inPeriod(o.dueDate)).map(o=>{const r=ruleById.get(o.ruleId),account=r?accountById.get(r.accountId):null;return{id:`recurring:${o.id}`,sourceId:o.id,kind:'recurring',status:o.status,dueDate:o.dueDate,title:o.description||r?.description||'Запланований платіж',accountId:r?.accountId||null,accountName:account?.name||'Рахунок',amountMinor:o.amountMinor??r?.amountMinor??0,currency:r?.currency||'UAH',action:'confirm_or_skip'};});const installments=plans.filter(p=>p.status!=='completed'&&p.status!=='cancelled').flatMap(p=>(p.obligations||[]).filter(o=>o.status!=='paid'&&inPeriod(o.dueDate)).map(o=>({id:`installment:${o.id}`,sourceId:o.id,kind:'installment',status:o.status,dueDate:o.dueDate,title:p.name,accountId:p.accountId,accountName:accountById.get(p.accountId)?.name||'Рахунок',amountMinor:o.amountMinor,currency:p.currency,action:'pay'})));const balances=accounts.map(account=>({account,balance:account.initialBalanceMinor+txs.reduce((sum,tx)=>sum+this.accountDeltaForPayment(account.id,tx),0)}));const creditCards=balances.filter(({account})=>account.type==='credit_card'&&account.creditLimitMinor!==null).map(({account,balance})=>{const dueDate=this.creditDeadline(account),amountMinor=Math.max(0,account.creditLimitMinor!-balance);return dueDate&&amountMinor>0&&inPeriod(dueDate)?{id:`credit-card:${account.id}`,sourceId:account.id,kind:'credit_card',status:'pending',dueDate,title:account.name,accountId:account.id,accountName:account.name,amountMinor,currency:account.currency,action:'manual'}:null;}).filter((row):row is NonNullable<typeof row>=>row!==null);const items=[...recurring,...installments,...creditCards].filter(item=>item.amountMinor>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.kind.localeCompare(b.kind)||a.title.localeCompare(b.title));const totals=Object.entries(items.reduce<Record<string,number>>((result,item)=>{result[item.currency]=(result[item.currency]||0)+item.amountMinor;return result;},{})).map(([currency,amountMinor])=>({currency,amountMinor}));return{period,items,totals};}
  async exportJson(){return{exportedAt:new Date().toISOString(),accounts:[],transactions:await this.transactions.find(),budgets:await this.budgets.find(),recurring:await this.rules.find(),installments:await this.plans.find()};}
  private daysUntil(to:string){const today=new Date();const end=new Date(`${to}T00:00:00Z`);return Math.max(0,Math.ceil((end.getTime()-today.getTime())/86400000));}
  private accountDeltaForPayment(id:string,tx:TransactionEntity){if(tx.type==='income'&&tx.accountId===id)return tx.amountMinor;if(tx.type==='expense'&&tx.accountId===id)return-tx.amountMinor;if(tx.type==='transfer_out'&&tx.accountId===id)return-tx.amountMinor;if(tx.type==='transfer_in'&&tx.accountId===id)return tx.amountMinor;if(tx.type==='transfer')return tx.accountId===id?-tx.amountMinor:tx.relatedAccountId===id?tx.amountMinor:0;return 0;}
  private creditDeadline(account:AccountEntity){if(!account.gracePeriodRule)return null;const values=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:process.env.TZ||'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));const year=Number(values.year),month=Number(values.month);if(!Number.isInteger(year)||!Number.isInteger(month))return null;if(account.gracePeriodRule==='next_month_end')return new Date(Date.UTC(year,month+1,0)).toISOString().slice(0,10);if(!account.gracePeriodDay)return null;const lastDay=new Date(Date.UTC(year,month+1,0)).getUTCDate();return new Date(Date.UTC(year,month,Math.min(account.gracePeriodDay,lastDay))).toISOString().slice(0,10);}
  private enqueue(type:string,payload:Record<string,unknown>){const now=new Date().toISOString();return this.outbox.save({id:randomUUID(),type,payload:JSON.stringify(payload),status:'pending',attempts:0,nextAttemptAt:now,createdAt:now});}
}
