import { ArrowLeft, ChartPie } from 'lucide-react';
import { financeApi } from '../api/client';
import { money } from '../lib/money';
import type { Account, Category } from '../types/finance';
import { TransactionList } from '../components/TransactionList';
import type { Transaction } from '../types/finance';

type AnalyticsData = Awaited<ReturnType<typeof financeApi.getAnalytics>>;
const colors=['#ffc35b','#ff7650','#8eb8ff','#b78cff','#73d6ae','#f18ac4'];
const piePath=(start:number,end:number,radius=100,center=110)=>{const point=(angle:number)=>{const radians=(angle-90)*Math.PI/180;return{x:center+radius*Math.cos(radians),y:center+radius*Math.sin(radians)}};if(end-start>=359.999){const top=point(0),bottom=point(180);return`M ${center} ${center} L ${top.x} ${top.y} A ${radius} ${radius} 0 1 1 ${bottom.x} ${bottom.y} A ${radius} ${radius} 0 1 1 ${top.x} ${top.y} Z`};const from=point(start),to=point(end);return`M ${center} ${center} L ${from.x} ${from.y} A ${radius} ${radius} 0 ${end-start>180?1:0} 1 ${to.x} ${to.y} Z`};
export function AnalyticsCategory({data,categoryId,type,accounts,categories,onBack}:{data:AnalyticsData;categoryId:string;type:'expense'|'income';accounts:Account[];categories:Category[];onBack:()=>void}){const name=(id:string|null)=>id==='direct'?'Прямі витрати':categories.find(category=>category.id===id)?.name||(type==='income'?'Доходи':'Витрати');const currency=(type==='expense'?data.expenses[0]?.currency:data.income[0]?.currency)||'UAH',rows=(type==='expense'?data.byCategory:data.incomeByCategory).filter(row=>row.currency===currency),total=rows.reduce((sum,row)=>sum+row.amountMinor,0);let offset=0;const source=type==='expense'?data.categoryTransactions:data.incomeCategoryTransactions;const transactions=source.map(item=>({...item,type,relatedAccountId:null,occurredAt:`${item.occurredOn}T12:00:00.000Z`})) as Transaction[];return <main className="screen analytics-screen analytics-drill-screen"><header className="screen-header"><button className="analytics-back" onClick={onBack}><ArrowLeft size={18}/> Аналітика</button><div className="round-action"><ChartPie/></div></header><section className="section-title"><h2>{name(categoryId)}</h2></section><div className="analytics-category-chart"><div className="analytics-pie"><svg viewBox="0 0 220 220" role="img" aria-label={`${type==='income'?'Доходи':'Витрати'}: ${name(categoryId)}`}>{rows.map((row,index)=>{const start=total?offset/total*360:0;offset+=row.amountMinor;const end=total?offset/total*360:360;return <path key={`${row.currency}:${row.categoryId}`} d={piePath(start,end)} fill={colors[index%colors.length]}/>})}</svg><div><strong>{money(total,currency)}</strong><small>У категорії</small></div></div><div className="analytics-legend">{rows.map((row,index)=><div key={`${row.currency}:${row.categoryId}`}><i style={{background:colors[index%colors.length]}}/><span>{name(row.categoryId)}</span><b>{money(row.amountMinor,row.currency)}</b></div>)}</div></div><section className="section-title"><h2>Транзакції</h2></section><TransactionList accounts={accounts} categories={categories} transactions={transactions}/></main>}
