import { ArrowLeft, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { BudgetDetails as BudgetDetailsData } from '../types/finance';
import { money } from '../lib/money';
import { TransactionList } from '../components/TransactionList';
import { AuthorLabel } from '../components/AuthorLabel';
import { TransactionDetailsDialog } from '../components/TransactionDetailsDialog';
import type { Transaction } from '../types/finance';

export function BudgetDetails({ data, accounts, categories, onBack, onEdit, onDelete }: { data: BudgetDetailsData; accounts: import('../types/finance').Account[]; categories: import('../types/finance').Category[]; onBack:()=>void; onEdit:()=>void; onDelete:()=>void }) {
  const [selectedTransaction,setSelectedTransaction]=useState<Transaction|null>(null);
  const monthKeys=Array.from({length:12},(_,index)=>{const date=new Date();date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-(11-index));return date.toISOString().slice(0,7)}); const amounts=new Map(data.monthlyExpenses.map(item=>[item.month,item.amountMinor])); const monthly=monthKeys.map(month=>({month,amountMinor:amounts.get(month)||0,currency:data.budget.currency})); const maxMonth=Math.max(1,...monthly.map(item=>item.amountMinor));
  return <main className="screen budget-details-screen"><header className="screen-header"><button className="round-action" onClick={onBack}><ArrowLeft/></button><h1>{data.budget.name}</h1><div className="planning-actions"><button aria-label="Редагувати бюджет" onClick={onEdit}><Pencil size={17}/></button><button aria-label="Видалити бюджет" onClick={onDelete}><Trash2 size={17}/></button></div></header><section className="budget-detail-summary"><div><small>Витрачено</small><strong>{money(data.budget.spentMinor,data.budget.currency)}</strong></div><div><small>Ліміт</small><strong>{money(data.budget.plannedAmountMinor,data.budget.currency)}</strong></div><div><small>Залишок</small><strong>{money(data.budget.remainingMinor,data.budget.currency)}</strong></div><AuthorLabel ownerId={data.budget.ownerId} ownerName={data.budget.ownerName}/><progress max="100" value={Math.min(100,data.budget.percentage)}/></section><section className="section-title"><h2>Витрати за останні 12 місяців</h2></section><div className="budget-month-chart">{monthly.map(item=><article key={item.month}><div className="budget-month-bar"><span style={{height:`${item.amountMinor/maxMonth*100}%`}}/></div><time>{item.month.slice(5)}/{item.month.slice(2,4)}</time><strong>{money(item.amountMinor,item.currency)}</strong></article>)}</div><section className="section-title"><h2>Транзакції</h2></section><TransactionList transactions={data.transactions} accounts={accounts} categories={categories} onTransactionClick={setSelectedTransaction}/>{selectedTransaction&&<TransactionDetailsDialog transaction={selectedTransaction} accounts={accounts} categories={categories} onClose={()=>setSelectedTransaction(null)}/>}</main>;
}
