import { useMemo, useState } from 'react';
import { Camera, MoreHorizontal, Pencil, Plus, Trash2, X } from 'lucide-react';
import { financeApi } from '../api/client';
import type { Account, Category, Project, Transaction, TransactionType } from '../types/finance';
import { money, parseMinor, shortDate } from '../lib/money';
import { PeriodPicker, type CustomRange, type PeriodPreset } from '../components/PeriodPicker';
import { CategoryOptions } from '../components/CategoryOptions';
import { CategoryIcon } from '../components/CategoryIcon';
import { QrScanner, type TaxQrData } from '../components/QrScanner';

type TaxItem = { name: string; quantity: number | null; priceMinor: number | null; amountMinor: number | null; vatMinor: number | null };
function accountLine(t: Transaction, accounts: Account[]) { const source = accounts.find(a => a.id === t.accountId)?.name || 'Рахунок'; return t.type === 'transfer' ? `${source} → ${accounts.find(a => a.id === t.relatedAccountId)?.name || 'Інший рахунок'}` : source; }
function metadataOf(t: Transaction): Record<string, unknown> { if (t.metadata) return t.metadata; try { return t.metadataJson ? JSON.parse(t.metadataJson) as Record<string, unknown> : {}; } catch { return {}; } }
function itemsOf(data: Record<string, unknown>): TaxItem[] { const tax = data.taxRegister as { items?: unknown } | undefined; if (Array.isArray(tax?.items)) return tax.items as TaxItem[]; return Array.isArray(data.items) ? data.items as TaxItem[] : []; }

export function Transactions({ transactions, accounts, categories, projects, period, range, taxApiEnabled, onPeriodChange, onRangeChange, onChanged }: { transactions: Transaction[]; accounts: Account[]; categories: Category[]; projects: Project[]; period: PeriodPreset; range: CustomRange; taxApiEnabled: boolean; onPeriodChange: (p: PeriodPreset) => void; onRangeChange: (range: CustomRange) => void; onChanged: () => void }) {
  const [filter, setFilter] = useState<'all' | TransactionType>('all'), [open, setOpen] = useState(false), [scannerOpen, setScannerOpen] = useState(false), [details, setDetails] = useState<Transaction | null>(null), [menuId, setMenuId] = useState<string | null>(null), [editing, setEditing] = useState<Transaction | null>(null);
  const [type, setType] = useState<TransactionType>('expense'), [accountId, setAccountId] = useState(accounts[0]?.id || ''), [relatedAccountId, setRelatedAccountId] = useState(accounts[1]?.id || ''), [amount, setAmount] = useState(''), [description, setDescription] = useState(''), [tags, setTags] = useState(''), [metadata, setMetadata] = useState<Record<string, unknown>>({}), [categoryId, setCategoryId] = useState(''), [projectId, setProjectId] = useState(''), [date, setDate] = useState(new Date().toISOString().slice(0, 10)), [error, setError] = useState('');
  const visible = useMemo(() => filter === 'all' ? transactions : transactions.filter(t => t.type === filter), [filter, transactions]);
  const reset = () => { setAmount(''); setDescription(''); setCategoryId(''); setProjectId(''); setTags(''); setMetadata({}); setError(''); setEditing(null); setOpen(false); setMenuId(null); };
  function scanTaxQr(data: TaxQrData) { setType('expense'); setAmount(data.amountMinor === undefined ? '' : String(data.amountMinor / 100).replace('.', ',')); setDescription(''); setDate(data.date || new Date().toISOString().slice(0, 10)); setCategoryId(''); setProjectId(''); setTags('чек, фіскальний'); setMetadata({ source: 'tax_register_pending', qr: { id: data.id, url: data.url, fn: data.fn || null, amountMinor: data.amountMinor ?? null } }); setScannerOpen(false); setError(''); setOpen(true); }
  const edit = (t: Transaction) => { setEditing(t); setType(t.type); setAccountId(t.accountId); setAmount(String(t.amountMinor / 100).replace('.', ',')); setDescription(t.description || ''); setCategoryId(t.categoryId || ''); setProjectId(t.projectId || ''); setDate(t.occurredAt.slice(0, 10)); setTags(t.tags?.join(', ') || ''); setMetadata(metadataOf(t)); setError(''); setOpen(true); };
  async function submit() { const amountMinor = parseMinor(amount); if (!accountId || !Number.isInteger(amountMinor) || amountMinor <= 0) return setError('Вкажіть коректну суму та рахунок'); if (!editing && type === 'transfer' && (!relatedAccountId || relatedAccountId === accountId)) return setError('Оберіть два різні рахунки'); try { if (editing) await financeApi.updateTransaction(editing.id, { type, accountId, amountMinor, occurredOn: date, description: description.trim() || undefined, categoryId: categoryId || undefined, projectId: projectId || undefined, tags: tags.split(',').map(v => v.trim()).filter(Boolean), metadata }); else if (type === 'transfer') await financeApi.createTransfer({ sourceAccountId: accountId, targetAccountId: relatedAccountId, sourceAmountMinor: amountMinor, targetAmountMinor: amountMinor, occurredOn: date, description: description.trim() || undefined }); else { const created = await financeApi.createTransaction({ type, accountId, amountMinor, occurredOn: date, description: description.trim() || undefined, categoryId: categoryId || undefined, projectId: projectId || undefined, tags: tags.split(',').map(v => v.trim()).filter(Boolean), metadata }); if (taxApiEnabled && metadata.source === 'tax_register_pending') { const qr = metadata.qr as { id: string; date?: string; fn?: string }; void financeApi.lookupTaxReceipt(qr).then(tax => financeApi.updateTransaction(created.id, { description: tax.description || undefined, metadata: { ...metadata, taxRegister: tax.metadata, source: 'tax_register' }, tags: tax.tags })).catch(() => undefined); } } reset(); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося зберегти операцію'); } }
  async function remove(t: Transaction) { if (!window.confirm('Видалити цю операцію?')) return; try { await financeApi.deleteTransaction(t.id); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося видалити'); } }
  async function refreshTaxReceipt(t: Transaction) { const data = metadataOf(t); const qr = data.qr as { id?: string; date?: string; fn?: string } | undefined; if (!qr?.id || !taxApiEnabled) return; try { const tax = await financeApi.lookupTaxReceipt(qr); const updated = await financeApi.updateTransaction(t.id, { description: tax.description || undefined, metadata: { ...data, taxRegister: tax.metadata, source: 'tax_register' }, tags: tax.tags }); setDetails(updated); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося оновити дані чека'); } }
  return <main className="screen"><header className="screen-header"><div><span className="eyebrow">ЖУРНАЛ ОПЕРАЦІЙ</span><h1>Транзакції</h1></div><div className="header-actions"><button className="round-action" aria-label="Додати чек" onClick={() => { setScannerOpen(true); setError(''); }}><Camera /></button><button className="round-action" aria-label="Додати транзакцію" onClick={() => { setEditing(null); setError(''); setOpen(true); }}><Plus /></button></div></header>
    <div className="transactions-toolbar"><PeriodPicker value={period} range={range} onChange={onPeriodChange} onRangeChange={onRangeChange} /></div><div className="category-tabs transaction-tabs">{(['all', 'income', 'expense', 'transfer'] as const).map(value => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{value === 'all' ? 'Всі' : value === 'income' ? 'Прибуток' : value === 'expense' ? 'Витрата' : 'Перекази'}</button>)}</div>
    <div className="transactions full-transactions">{!visible.length && <p className="empty">Операцій за цим періодом немає</p>}{visible.map(t => <article className="transaction" key={t.id} onClick={() => setDetails(t)}><time>{shortDate(t.occurredAt)}</time><div className={`transaction-icon ${t.type}`}>{t.type === 'transfer' ? '↔' : <CategoryIcon name={categories.find(c => c.id === t.categoryId)?.icon} color={categories.find(c => c.id === t.categoryId)?.color} />}</div><div className="transaction-copy"><strong>{t.description || categories.find(c => c.id === t.categoryId)?.name || (t.type === 'income' ? 'Надходження' : t.type === 'transfer' ? 'Переказ' : 'Витрата')}</strong><span>{accountLine(t, accounts)}</span></div><b className={t.type === 'income' ? 'income' : ''}>{t.type === 'income' ? '+' : t.type === 'transfer' ? '' : '−'} {money(t.amountMinor, t.currency)}</b></article>)}</div>
    {scannerOpen && <div className="modal"><section><button className="modal-close" onClick={() => setScannerOpen(false)}><X /></button><h2>Додати чек</h2><QrScanner onScan={scanTaxQr} onError={setError} /></section></div>}
    {details && <div className="modal"><section className="transaction-details"><button className="modal-close" onClick={() => setDetails(null)}><X /></button><h2>Деталі транзакції</h2><p><strong>{details.description || 'Без опису'}</strong><br />{shortDate(details.occurredAt)} · {accountLine(details, accounts)}</p><p className={details.type === 'income' ? 'income' : ''}>{details.type === 'income' ? '+' : details.type === 'transfer' ? '' : '−'} {money(details.amountMinor, details.currency)}</p>{details.tags?.length ? <p>Теги: {details.tags.join(', ')}</p> : null}{(() => { const data = metadataOf(details); const qr = data.qr as { id?: string; url?: string; fn?: string } | undefined; const items = itemsOf(data); return <>{qr && <p>Фіскальний чек: {qr.id}{qr.fn ? ` · РРО ${qr.fn}` : ''}{qr.url && <><br /><a href={qr.url} target="_blank" rel="noreferrer">Відкрити чек у ДПС</a></>}<br /><button className="secondary-action" onClick={() => void refreshTaxReceipt(details)}>Оновити дані чека</button></p>}{items.length > 0 && <div className="receipt-items"><h3>Позиції чека</h3>{items.map((item, i) => <div className="receipt-item" key={`${item.name}-${i}`}><span>{item.name}{item.quantity ? ` · ${item.quantity} шт.` : ''}</span><b>{item.amountMinor === null ? '—' : money(item.amountMinor, details.currency)}</b><small>{item.priceMinor === null ? '' : `Ціна: ${money(item.priceMinor, details.currency)} `}{item.vatMinor === null ? '' : `· ПДВ: ${money(item.vatMinor, details.currency)}`}</small></div>)}</div>}</>; })()}<div className="transaction-detail-actions"><button className="secondary-action" onClick={() => { setDetails(null); edit(details); }}><Pencil size={15} />Редагувати</button><button className="danger-action" onClick={() => { void remove(details); setDetails(null); }}><Trash2 size={15} />Видалити</button></div></section></div>}
    {open && <div className="modal"><section><button className="modal-close" onClick={reset}><X /></button><h2>{editing ? 'Редагувати операцію' : 'Нова операція'}</h2><label>Тип<select value={type} disabled={!!editing} onChange={event => { const next = event.target.value as TransactionType; setType(next); if (next !== 'expense') setProjectId(''); }}><option value="expense">Витрата</option><option value="income">Прибуток</option>{!editing && <option value="transfer">Переказ</option>}</select></label><label>Сума<input inputMode="decimal" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0,00" /></label><label>Дата<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label>Рахунок<select value={accountId} onChange={event => setAccountId(event.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{!editing && type === 'transfer' ? <label>На рахунок<select value={relatedAccountId} onChange={event => setRelatedAccountId(event.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label> : <label>Категорія<select value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">Без категорії</option><CategoryOptions categories={categories} type={type === 'income' ? 'income' : 'expense'} /></select></label>}{type === 'expense' && <label>Проєкт<select value={projectId} onChange={event => setProjectId(event.target.value)}><option value="">Без проєкту</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Теги<input value={tags} onChange={event => setTags(event.target.value)} placeholder="чек, продукти" /></label><label>Опис<input value={description} onChange={event => setDescription(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" onClick={() => void submit()}>{editing ? 'Зберегти зміни' : 'Зберегти'}</button></section></div>}
  </main>;
}
