import { useEffect, useMemo, useRef, useState } from 'react';
import { Calendar, Camera, Settings, X } from 'lucide-react';
import { financeApi } from '../api/client';
import type { Account, Category, Project, Transaction, TransactionType } from '../types/finance';
import { parseMinor } from '../lib/money';
import { PeriodPicker, type CustomRange, type PeriodPreset } from '../components/PeriodPicker';
import { CategoryOptions } from '../components/CategoryOptions';
import { QrScanner, type TaxQrData } from '../components/QrScanner';
import { getLastTransactionAccount, rememberTransactionAccount } from '../lib/transaction-preferences';
import { TransactionFab } from '../components/TransactionFab';
import { TransactionList } from '../components/TransactionList';
import { TransactionDetailsDialog } from '../components/TransactionDetailsDialog';

function metadataOf(t: Transaction): Record<string, unknown> { if (t.metadata) return t.metadata; try { return t.metadataJson ? JSON.parse(t.metadataJson) as Record<string, unknown> : {}; } catch { return {}; } }
function localDate() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; }
function localTime() { const now = new Date(); return `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`; }
function displayDate(value: string) { const [year, month, day] = value.split('-'); return year && month && day ? `${day}.${month}.${year}` : ''; }
function maskDate(value: string) { const digits = value.replace(/\D/g, '').slice(0, 8); return [digits.slice(0, 2), digits.slice(2, 4), digits.slice(4)].filter(Boolean).join('.'); }
function isoDate(value: string) { const match = /^(\d{2})\.(\d{2})\.(\d{4})$/.exec(value); if (!match) return null; const [, day, month, year] = match; const date = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day))); return date.getUTCFullYear() === Number(year) && date.getUTCMonth() === Number(month) - 1 && date.getUTCDate() === Number(day) ? `${year}-${month}-${day}` : null; }

export function Transactions({ transactions, accounts, categories, projects, period, range, taxApiEnabled, quickCreate, onQuickCreateHandled, onSettings, onPeriodChange, onRangeChange, onChanged }: { transactions: Transaction[]; accounts: Account[]; categories: Category[]; projects: Project[]; period: PeriodPreset; range: CustomRange; taxApiEnabled: boolean; quickCreate?: boolean; onQuickCreateHandled?: () => void; onSettings?: () => void; onPeriodChange: (p: PeriodPreset) => void; onRangeChange: (range: CustomRange) => void; onChanged: () => void }) {
  const [filter, setFilter] = useState<'all' | TransactionType>('all'), [open, setOpen] = useState(false), [scannerOpen, setScannerOpen] = useState(false), [details, setDetails] = useState<Transaction | null>(null), [editing, setEditing] = useState<Transaction | null>(null);
  const [type, setType] = useState<TransactionType>('expense'), [accountId, setAccountId] = useState(() => getLastTransactionAccount(accounts[0]?.id || '')), [relatedAccountId, setRelatedAccountId] = useState(accounts[1]?.id || ''), [amount, setAmount] = useState(''), [description, setDescription] = useState(''), [tags, setTags] = useState(''), [metadata, setMetadata] = useState<Record<string, unknown>>({}), [categoryId, setCategoryId] = useState(''), [projectId, setProjectId] = useState(''), [date, setDate] = useState(displayDate(localDate())), [time, setTime] = useState(localTime()), [error, setError] = useState('');
  const dateInput = useRef<(HTMLInputElement & { showPicker?: () => void })>(null);
  useEffect(() => { if (quickCreate) { setEditing(null); setError(''); setOpen(true); onQuickCreateHandled?.(); } }, [quickCreate, onQuickCreateHandled]);
  const visible = useMemo(() => filter === 'all' ? transactions : transactions.filter(t => t.type === filter), [filter, transactions]);
  const reset = () => { rememberTransactionAccount(accountId); setAmount(''); setDescription(''); setCategoryId(''); setProjectId(''); setTags(''); setMetadata({}); setError(''); setEditing(null); setOpen(false); };
  function scanTaxQr(data: TaxQrData) { setType('expense'); setAmount(data.amountMinor === undefined ? '' : String(data.amountMinor / 100).replace('.', ',')); setDescription(''); setDate(displayDate(data.date || localDate())); setTime(localTime()); setCategoryId(''); setProjectId(''); setTags('чек, фіскальний'); setMetadata({ source: 'tax_register_pending', qr: { id: data.id, url: data.url, fn: data.fn || null, amountMinor: data.amountMinor ?? null } }); setScannerOpen(false); setError(''); setOpen(true); }
  const edit = (t: Transaction) => { setEditing(t); setType(t.type); setAccountId(t.accountId); setAmount(String(t.amountMinor / 100).replace('.', ',')); setDescription(t.description || ''); setCategoryId(t.categoryId || ''); setProjectId(t.projectId || ''); setDate(displayDate(t.occurredOn || t.occurredAt.slice(0, 10))); setTime(t.occurredAt.endsWith('T12:00:00.000Z') ? '12:00' : `${new Date(t.occurredAt).getHours().toString().padStart(2, '0')}:${new Date(t.occurredAt).getMinutes().toString().padStart(2, '0')}`); setTags(t.tags?.join(', ') || ''); setMetadata(metadataOf(t)); setError(''); setOpen(true); };
  async function submit() { const amountMinor = parseMinor(amount); const normalizedDate = isoDate(date); if (!normalizedDate || !/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) return setError('Вкажіть коректні дату та час'); if (!accountId || !Number.isInteger(amountMinor) || amountMinor <= 0) return setError('Вкажіть коректну суму та рахунок'); if (!editing && type === 'transfer' && (!relatedAccountId || relatedAccountId === accountId)) return setError('Оберіть два різні рахунки'); const occurredAt = `${normalizedDate}T${time}:00.000Z`; try { if (editing) await financeApi.updateTransaction(editing.id, { type, accountId, amountMinor, occurredOn: normalizedDate, occurredAt, description: description.trim() || undefined, categoryId: categoryId || undefined, projectId: projectId || undefined, tags: tags.split(',').map(v => v.trim()).filter(Boolean), metadata }); else if (type === 'transfer') await financeApi.createTransfer({ sourceAccountId: accountId, targetAccountId: relatedAccountId, sourceAmountMinor: amountMinor, targetAmountMinor: amountMinor, occurredOn: normalizedDate, occurredAt, description: description.trim() || undefined }); else { const created = await financeApi.createTransaction({ type, accountId, amountMinor, occurredOn: normalizedDate, occurredAt, description: description.trim() || undefined, categoryId: categoryId || undefined, projectId: projectId || undefined, tags: tags.split(',').map(v => v.trim()).filter(Boolean), metadata }); if (taxApiEnabled && metadata.source === 'tax_register_pending') { const qr = metadata.qr as { id: string; date?: string; fn?: string }; void financeApi.lookupTaxReceipt(qr).then(tax => financeApi.updateTransaction(created.id, { description: tax.description || undefined, metadata: { ...metadata, taxRegister: tax.metadata, source: 'tax_register' }, tags: tax.tags })).catch(() => undefined); } } reset(); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося зберегти операцію'); } }
  async function remove(t: Transaction) { if (!window.confirm('Видалити цю операцію?')) return; try { await financeApi.deleteTransaction(t.id); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося видалити'); } }
  async function refreshTaxReceipt(t: Transaction) { const data = metadataOf(t); const qr = data.qr as { id?: string; date?: string; fn?: string } | undefined; if (!qr?.id || !taxApiEnabled) return; try { const tax = await financeApi.lookupTaxReceipt(qr); const updated = await financeApi.updateTransaction(t.id, { description: tax.description || undefined, metadata: { ...data, taxRegister: tax.metadata, source: 'tax_register' }, tags: tax.tags }); setDetails(updated); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося оновити дані чека'); } }
  return <main className="screen"><header className="screen-header"><div><span className="eyebrow">ЖУРНАЛ ОПЕРАЦІЙ</span><h1>Транзакції</h1></div><div className="header-actions"><button className="round-action settings-action" aria-label="Налаштування" onClick={() => onSettings?.()}><Settings /></button></div></header>
    <div className="transactions-toolbar"><PeriodPicker value={period} range={range} onChange={onPeriodChange} onRangeChange={onRangeChange} /></div><div className="category-tabs transaction-tabs">{(['all', 'income', 'expense', 'transfer'] as const).map(value => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{value === 'all' ? 'Всі' : value === 'income' ? 'Прибуток' : value === 'expense' ? 'Витрата' : 'Перекази'}</button>)}</div>
    <TransactionList transactions={visible} accounts={accounts} categories={categories} limit={visible.length} onTransactionClick={setDetails} />
    {scannerOpen && <div className="modal"><section><button className="modal-close" onClick={() => setScannerOpen(false)}><X /></button><h2>Додати чек</h2><QrScanner onScan={scanTaxQr} onError={setError} /></section></div>}
    {details && <TransactionDetailsDialog transaction={details} accounts={accounts} categories={categories} taxApiEnabled={taxApiEnabled} onClose={() => setDetails(null)} onEdit={transaction => { setDetails(null); edit(transaction); }} onDelete={transaction => { void remove(transaction); setDetails(null); }} onRefreshTaxReceipt={transaction => void refreshTaxReceipt(transaction)}/>}
    {open && <div className="modal"><section><button className="modal-close" onClick={reset}><X /></button><div className="transaction-form-title"><h2>{editing ? 'Редагувати операцію' : 'Нова операція'}</h2>{!editing && <button className="secondary-action qr-form-action" onClick={() => { setOpen(false); setScannerOpen(true); setError(''); }}><Camera size={16} /> Заповнити через QR</button>}</div><label>Тип<select value={type} disabled={!!editing} onChange={event => { const next = event.target.value as TransactionType; setType(next); if (next !== 'expense') setProjectId(''); }}><option value="expense">Витрата</option><option value="income">Прибуток</option>{!editing && <option value="transfer">Переказ</option>}</select></label><label>Сума<input inputMode="decimal" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0,00" /></label><label>Дата<div className="date-input-row"><input value={date} onChange={event => setDate(maskDate(event.target.value))} placeholder="ДД.ММ.РРРР" inputMode="numeric" maxLength={10} /><input ref={dateInput} className="date-picker-input" type="date" tabIndex={-1} aria-hidden="true" value={isoDate(date) || ''} onChange={event => setDate(displayDate(event.target.value))} /><button type="button" aria-label="Відкрити календар" onClick={() => { const input = dateInput.current; if (!input) return; if (typeof (input as unknown as { showPicker?: unknown }).showPicker === 'function') (input as unknown as { showPicker: () => void }).showPicker(); else input.click(); }}><Calendar size={18} /></button></div></label><label>Час<input type="time" value={time} onChange={event => setTime(event.target.value)} step="60" /></label><label>Рахунок<select value={accountId} onChange={event => setAccountId(event.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{!editing && type === 'transfer' ? <label>На рахунок<select value={relatedAccountId} onChange={event => setRelatedAccountId(event.target.value)}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label> : <label>Категорія<select value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">Без категорії</option><CategoryOptions categories={categories} type={type === 'income' ? 'income' : 'expense'} /></select></label>}{type === 'expense' && <label>Проєкт<select value={projectId} onChange={event => setProjectId(event.target.value)}><option value="">Без проєкту</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Теги<input value={tags} onChange={event => setTags(event.target.value)} placeholder="чек, продукти" /></label><label>Опис<input value={description} onChange={event => setDescription(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary" onClick={() => void submit()}>{editing ? 'Зберегти зміни' : 'Зберегти'}</button></section></div>}
    <TransactionFab onClick={() => { setEditing(null); setError(''); setOpen(true); }} />
  </main>;
}
