import type { Account, AppSettings, Budget, BudgetProgress, Category, CreditSummary, CreditTerms, ImportReport, InstallmentPlan, PaymentsReport, Project, ReceiptDraft, RecurringOccurrence, RecurringRule, RuntimeConfig, Transaction, User } from '../types/finance';

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`./api/${path}`, { headers: { 'Content-Type': 'application/json', ...init?.headers }, ...init });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.message || 'Не удалось выполнить запрос');
  return response.status === 204 ? undefined as T : response.json() as Promise<T>;
}

export const financeApi = {
  getAccounts: () => request<Account[]>('accounts'),
  getTransactions: (preset = 'current_month',range?:{from:string;to:string}) => request<{ items: Transaction[] }>(`transactions?${preset==='custom'&&range?`from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`:`preset=${encodeURIComponent(preset)}`}`).then(result => result.items),
  getCategories: () => request<Category[]>('categories'),
  getProjects: () => request<Project[]>('projects'),
  getMe: () => request<User>('me'),
  getUsers: () => request<User[]>('users'),
  setUserAccess: (id:string,blocked:boolean) => request<User>(`users/${id}/access`,{method:'PATCH',body:JSON.stringify({blocked})}),
  deleteAccount: (id: string) => request<void>(`accounts/${id}`, { method: 'DELETE' }),
  createAccount: (body: Record<string, unknown>) => request<Account>('accounts', { method: 'POST', body: JSON.stringify(body) }),
  updateAccount: (id:string,body:Record<string,unknown>) => request<Account>(`accounts/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  archiveAccount: (id:string) => request<Account>(`accounts/${id}/archive`,{method:'POST'}),
  createCategory: (body: Record<string, unknown>) => request<Category>('categories', { method: 'POST', body: JSON.stringify(body) }),
  updateCategory: (id: string, body: Record<string, unknown>) => request<Category>(`categories/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  deleteCategory: (id: string) => request<void>(`categories/${id}`, { method: 'DELETE' }),
  createProject: (body: Record<string, unknown>) => request<Project>('projects', { method: 'POST', body: JSON.stringify(body) }),
  deleteProject: (id: string) => request<void>(`projects/${id}`, { method: 'DELETE' }),
  updateProject: (id:string,body:Record<string,unknown>) => request<Project>(`projects/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  archiveProject: (id:string) => request<Project>(`projects/${id}/archive`,{method:'POST'}),
  createTransaction: (body: Record<string, unknown>) => request<Transaction>('transactions', { method: 'POST', body: JSON.stringify(body) }),
  createTransfer: (body:Record<string,unknown>) => request<Record<string,unknown>>('transfers',{method:'POST',body:JSON.stringify(body)}),
  updateTransaction: (id: string, body: Record<string, unknown>) => request<Transaction>(`transactions/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  deleteTransaction: (id: string) => request<void>(`transactions/${id}`, { method: 'DELETE' }),
  getBudgets: () => request<BudgetProgress[]>('budgets'),
  getBudgetProgress: (id: string) => request<BudgetProgress>(`budgets/${id}/progress`),
  createBudget: (body: Record<string, unknown>) => request<Budget>('budgets', { method: 'POST', body: JSON.stringify(body) }),
  updateBudget: (id:string,body:Record<string,unknown>) => request<BudgetProgress>(`budgets/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  rolloverBudget: (id:string) => request<BudgetProgress>(`budgets/${id}/rollover`,{method:'POST'}),
  deleteBudget: (id:string) => request<void>(`budgets/${id}`,{method:'DELETE'}),
  getRecurring: () => request<RecurringRule[]>('recurring'),
  createRecurring: (body: Record<string, unknown>) => request<RecurringRule>('recurring', { method: 'POST', body: JSON.stringify(body) }),
  deleteRecurring: (id:string) => request<void>(`recurring/${id}`,{method:'DELETE'}),
  updateRecurring: (id:string,body:Record<string,unknown>) => request<RecurringRule>(`recurring/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  getOccurrences: () => request<RecurringOccurrence[]>('recurring/occurrences'),
  confirmOccurrence: (id:string, accountId:string) => request<RecurringOccurrence>(`recurring/occurrences/${id}/confirm`,{method:'POST',body:JSON.stringify({accountId})}),
  skipOccurrence: (id:string) => request<RecurringOccurrence>(`recurring/occurrences/${id}/skip`,{method:'POST'}),
  generateOccurrences: () => request<{created:number}>('recurring/generate',{method:'POST',body:'{}'}),
  getInstallments: () => request<InstallmentPlan[]>('installments'),
  getPayments: (preset = 'current_month', range?: { from: string; to: string }) => request<PaymentsReport>(`payments?${preset === 'custom' && range ? `from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}` : `preset=${encodeURIComponent(preset)}`}`),
  createInstallment: (body:Record<string,unknown>) => request<InstallmentPlan>('installments',{method:'POST',body:JSON.stringify(body)}),
  updateInstallment: (id:string,body:Record<string,unknown>) => request<InstallmentPlan>(`installments/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  deleteInstallment: (id:string) => request<{deleted:boolean;cancelled:boolean}>(`installments/${id}`,{method:'DELETE'}),
  payObligation: (id:string) => request<void>(`installments/obligations/${id}/pay`,{method:'POST'}),
  repayInstallment: (id:string) => request<void>(`installments/${id}/repay-early`,{method:'POST'}),
  getCreditTerms: (id:string) => request<CreditTerms|null>(`accounts/${id}/credit-terms`),
  saveCreditTerms: (id:string,body:Record<string,unknown>) => request<CreditTerms>(`accounts/${id}/credit-terms`,{method:'PUT',body:JSON.stringify(body)}),
  getCreditSummary: (id:string) => request<CreditSummary>(`accounts/${id}/credit-summary`),
  previewImport: (body:Record<string,unknown>) => request<ImportReport>('imports/preview',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)}),
  getImport: (id:string) => request<ImportReport>(`imports/${id}`),
  confirmImport: (id:string) => request<ImportReport>(`imports/${id}/confirm`,{method:'POST'}),
  cancelImport: (id:string) => request<ImportReport>(`imports/${id}/cancel`,{method:'POST'}),
  getReceipts: () => request<ReceiptDraft[]>('receipts'),
  createReceipt: (body:Record<string,unknown>) => request<ReceiptDraft>('receipts',{method:'POST',body:JSON.stringify(body)}),
  updateReceipt: (id:string,body:Record<string,unknown>) => request<ReceiptDraft>(`receipts/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  confirmReceipt: (id:string) => request<ReceiptDraft>(`receipts/${id}/confirm`,{method:'POST'}),
  cancelReceipt: (id:string) => request<ReceiptDraft>(`receipts/${id}/cancel`,{method:'POST'}),
  deleteReceipt: (id:string) => request<void>(`receipts/${id}`,{method:'DELETE'}),
  getRuntimeConfig: () => request<RuntimeConfig>('config'),
  getSettings: () => request<AppSettings>('settings'),
  saveSettings: (body:AppSettings) => request<AppSettings>('settings',{method:'PUT',body:JSON.stringify(body)}),
  exportData: () => request<Record<string,unknown>>('export'),
  getAnalytics: (preset = 'current_month', range?: { from: string; to: string }) => request<{ period:{from:string;to:string};income:{currency:string;amountMinor:number}[];expenses:{currency:string;amountMinor:number}[];net:{currency:string;amountMinor:number}[];byCategory:{currency:string;categoryId:string;amountMinor:number}[];trend:{date:string;currency:string;incomeMinor:number;expenseMinor:number}[];largestExpenses:{id:string;amountMinor:number;currency:string;description:string|null;occurredOn:string;categoryId:string|null;accountId:string;projectId:string|null}[] }>(`analytics?${preset === 'custom' && range ? `from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}` : `preset=${encodeURIComponent(preset)}`}`),
};
